[technote]
id = "SITCOMTN-150"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-150.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-150"
github_default_branch = "main"
date_created = 2024-11-22T02:33:17Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Enrico"
name.family = "Giro"
internal_id = "egi"
orcid = "https://orcid.org/0000-0001-7301-8285"
[[technote.authors.affiliations]]
name = "INAF - OA Trieste"
internal_id = "OATS"
address = "Via G.B. Tiepolo 11 - 34143 Trieste (TS), ITALY"

[[technote.authors]]
name.given = "Gabriele"
name.family = "Rodeghiero"
internal_id = "gro"
orcid = "https://orcid.org/0000-0002-3469-9863"
[[technote.authors.affiliations]]
name = "INAF - OA Bologna"
internal_id = "OABO"
address = "Via Piero Gobetti 93/3 - 30129 Bologna, ITALY"

[[technote.authors]]
name.given = "Luca"
name.family = "Rosignoli"
internal_id = "lro"
orcid = "https://orcid.org/0000-0002-3469-9863"
[[technote.authors.affiliations]]
name = "INAF - OA Bologna"
internal_id = "OABO"
address = "Via Piero Gobetti 93/3 - 30129 Bologna, ITALY"

[[technote.authors]]
name.given = "Rodolfo"
name.family = "Canestrari"
internal_id = "rca"
orcid = "0000-0003-4591-7763"
[[technote.authors.affiliations]]
name = "INAF - IASF Palermo"
internal_id = "IASFPA"
address = "Via Ugo la Malfa, 153, 90146 Palermo, ITALY"

